### PR TITLE
Added Azure Blueprints Blog

### PR DESCRIPTION
**Pull request by JochemTan**

### CODE REVIEW

**Comment by DibranMulder** [comment]
Feedback:
- Names start with a capital letter, e.g: Azure

Case Description
- Organisations lack the tools to enforce the Governance of Azure resources.
- To use the analogy you mentioned, if people build a treehouse we always want it build this or that way.
- We want to make sure that we don't have to check afterwards but can do a check upfront.
- We want to make this as less bureaucratic as possible.
- Blueprints allows us to check upon the created Azure resources and make sure that they comply to the set of rules made by the enterprise.

- Yields: Compliance, No bottlenecks

**Comment by JochemTan** [comment]
I did not fully understand what was ment with **doing the check upfront instead of afterwards** as you can check if the the rules on the blueprint are really applied if it is released.

**Comment by DibranMulder** [comment]
> I did not fully understand what was ment with **doing the check upfront instead of afterwards** as you can check if the the rules on the blueprint are really applied if it is released.

Oh I meant that you don't want to enforce Governance when things are already deployed to Azure. You want to have some gate keeping.

**Comment by DibranMulder** [comment]
It would be great if you could also add some ways to create some blueprints as code instead of clicking in the portal. Maybe some very small ARM or Azure CLI demo's. Just add it as another chapter called 'Blueprints as code' or something like that. 

There is still one azure without a capital A.

**Comment by DibranMulder** [comment]
Last feedback please, at the create blueprint section a JSON file is being created but it is cutoff strangely. I'm talking about the blueprint.json file. Its looks like the text starting the following is in the middle of the file 
> Azure Blueprints makes it possible to create a repeatable 


Please also take a look at how I setup the styling for the code. It now has syntax highlighting.

**Comment by JochemTan** [comment]
I fixed the problem at the create blueprint section at the JSON file. I also moved the text that was under the create blueprint section to the beginning of the file as it seemed better there then the original position that it was in. 

Also I really like the image that was added and the syntax highlighting that was done!

**Pull request merged**
